[project]
name = "data-modeling-svartfika-de24"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mimesis>=18.0.0",
    "psycopg[binary,pool]>=3.2.6",
    "pydantic-settings>=2.8.1",
    "pydantic>=2.11.1",
    "sqlalchemy>=2.0.40",
]
